### ISSUE TITLE
Create ERDs - Entity Relationship diagram

### ISSUE THREAD

**Issue by PhyllisWong** [SF-Gov/Back-End#2]
Use something like LucidChart to create this document. This will look really good in our README.md to help other developers use our service.

**Comment by jayceazua** [comment]
[SFGov-ERD-Sequence-Flow.pdf](https://github.com/SF-Gov/Back-End/files/2431360/SFGov-ERD-Sequence-Flow.pdf)

**Comment by PhyllisWong** [comment]
This looks great Jayce. Can you make sure this doc is in the Google Folder?
