### ISSUE TITLE
Create Sequence Diagram

### ISSUE THREAD

**Issue by PhyllisWong** [SF-Gov/Back-End#4]
- [x] LucidChart the data flow
Questions:
- [x] Where does the data start
- [x] What Service does the data go through before it gets to the user?
- [x] How is the data manipulated? 
- [x] Where is it stored?

**Comment by jayceazua** [comment]
[SFGov-ERD-Sequence-Flow.pdf](https://github.com/SF-Gov/Back-End/files/2431359/SFGov-ERD-Sequence-Flow.pdf)

**Comment by PhyllisWong** [comment]
The sequence diagram needs a revision. It looks like this is the same document as the ERD doc, but they should be different and have different purposes. I'm attaching a screen shot of what a sequence diagram looks like.
<img width="550" alt="screen shot 2018-10-01 at 12 31 15 pm" src="https://user-images.githubusercontent.com/24304039/46311065-f231de00-c575-11e8-8e6d-878a3e7969f8.png">

**Comment by pomfy113** [comment]
For ERD, the "Sections of Available Dates"'s contents will probably be change depending on what the API spits out. Same with "15 minute selected section"s. I have doubts about it being Dates/Array of Dates.

Besides that, everything looks straightforward and there's nothing much to change. There doesn't appear to be anything missing.
